version: "3.3"

services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    command: '--default-authentication-plugin=mysql_native_password'  
    networks:
      - backend

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.0-fpm
    container_name: wordpress
    volumes:
      - ./html:/var/www/html
        #    ports:
            #      - "9090:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - backend

  phpmyadmin:
    depends_on:
      - db          
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      VIRTUAL_HOST: phpmyadmin.local            
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root        
    networks:
      - backend
      - frontend        

  nginx:
    image: nginx
    container_name: nginx
    environment:
      - VIRTUAL_HOST=wp.local
    depends_on:
      - wordpress
    volumes:
      - ./default.nginx:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    networks:
      - backend      
      - frontend
      

        
networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    external:
      name: proxy


